server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: a-string-secret-at-least-256-bits-long
  datasource:
    write:
      url: ${SPRING_DATASOURCE_WRITE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
    read:
      url: ${SPRING_DATASOURCE_READ_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}


  flyway:
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG