package com.paragon.domain.enums;

public enum AuditEntryActionType {
    VIEW_ACCOUNT_LIST,
    REGISTER_ACCOUNT,
    ASSIGN_PERMISSIONS,
    DISABLE_ACCOUNT,
    ENABLE_ACCOUNT,
    ACCOUNT_LOCKED,
    MODIFY_ACCOUNT_DETAILS,
    LOGIN,
    VIEW_PROFILE,
    REQUEST_PASSWORD_CHANGE,
    APPROVE_PASSWORD_CHANGE,
    RESET_ACCOUNT_PASSWORD,
    FORCED_PASSWORD_RESET_LOGIN,
    CHANGE_PASSWORD,
    FORCE_LOGOUT_ON_PASSWORD_CHANGE,

    VIEW_LOGIN_LOGS,
    VIEW_PASSWORD_CHANGE_LOGS,
    VIEW_MODMAIL_LOGS,
    VIEW_WOOCOMMERCE_LOGS,

    VIEW_TRANSCRIPT_LIST,
    FILTER_TRANSCRIPTS,
    VIEW_TRANSCRIPT,
    CREATE_TRANSCRIPT_SHARE_LINK,
    DISABLE_TRANSCRIPT_SHARE_LINK,

    VIEW_BACKUP_LIST,
    ACCESS_BACKUP_CONTENT,
    LOAD_BACKUP_CONTENT,

    VIEW_SYNCED_MEMBERS,
    MIGRATE_SYNCED_MEMBERS,

    VIEW_ORDER_LIST,
    FILTER_ORDERS,
    VIEW_ORDER,
    REQUEST_CENSORED_ORDER_CONTENT,
    APPROVE_CENSORED_ORDER_CONTENT,
    VIEW_CENSORED_ORDER_CONTENT,
    CREATE_ORDER_SHARE_LINK,
    DISABLE_ORDER_SHARE_LINK,

    VIEW_PRODUCT_LIST,
    VIEW_PRODUCT_STOCK_COUNT,
    VIEW_PRODUCT_SALES_COUNT,

    VIEW_EARLY_DISPUTE_WARNINGS,
    RECEIVE_DISPUTE_WARNING_NOTIFICATION
}
